#Example config for breakpointer.smk workflow
species:
  sp1:
    genome: /path/to/your/genome
    num_chr: 10
  sp2:
    genome: /path/to/your/genome
    num_chr: 10
  sp3:
    genome: /path/to/your/genome
    num_chr: 10
  sp4:
    genome: /path/to/your/genome
    num_chr: 12
#Minimap2 parameter, see minimap2 manual for details (type of sequencing, etc.)
#seq_arg: "-cx asm20"
#breakpointer2 parameters
len_co: 75000
len_bp: 4000000
q: 30
FET: 100000
bp_co: 500000
